---
name: plasma
version: 5.9
summary: wow
description: phew
confinement: classic
grade: stable

apps:
    plasma:
        command: bash
        slots: [mir, upower-observe]
        plugs:
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
        - network-manager
        - plasma
        - udisks2

slots:
    kglobalaccel-dbus:
        interface: dbus
        bus: session
        name: org.kde.kglobalaccel
    plasma-dbus:
        interface: dbus
        bus: session
        name: org.kde.plasmashell
    kded-dbus:
        interface: dbus
        bus: session
        name: org.kde.kded5
    plasmanm-dbus:
        interface: dbus
        bus: session
        name: org.kde.plasmanetworkmanagement
    kwin-dbus:
        interface: dbus
        bus: session
        name: org.kde.KWin
    klauncher-dbus:
        interface: dbus
        bus: session
        name: org.kde.klauncher5
    ksplash-dbus:
        interface: dbus
        bus: session
        name: org.kde.KSplash
    screensaver-dbus:
        interface: dbus
        bus: session
        name: org.kde.screensaver
    ksmserver-dbus:
        interface: dbus
        bus: session
        name: org.kde.ksmserver
    krunner-dbus:
        interface: dbus
        bus: session
        name: org.kde.krunner
    statusnotifierwatcher-dbus:
        interface: dbus
        bus: session
        name: org.kde.StatusNotifierWatcher
    kappmenu-dbus:
        interface: dbus
        bus: session
        name: org.kde.kappmenu
    kcookiejar-dbus:
        interface: dbus
        bus: session
        name: org.kde.kcookiejar5
    kcminit-dbus:
        interface: dbus
        bus: session
        name: org.kde.kcminit
    kaccess-dbus:
        interface: dbus
        bus: session
        name: org.kde.kaccess
    activitymanager-dbus:
        interface: dbus
        bus: session
        name: org.kde.ActivityManager
    statusnotifierhost-dbus:
        interface: dbus
        bus: session
        name: org.kde.StatusNotifierHost
    kuiserver-dbus:
        interface: dbus
        bus: session
        name: org.kde.kuiserver
    fdo-screensaver-dbus:
        interface: dbus
        bus: session
        name: org.freedesktop.ScreenSaver
    fdo-notifications-dbus:
        interface: dbus
        bus: session
        name: org.freedesktop.Notifications

parts:
    plasma:
        stage-packages: [plasma-workspace-wayland, plasma-desktop, gdb, strace, vim, kwin-wayland-backend-x11, libxkbcommon-x11-0, libxkbcommon0, libx11-data, xkb-data, ltrace, kwrite, plasma-workspace, konsole, kwin-wayland-backend-drm, libqt5sql5-sqlite]
        plugin: dump
        source: empty
        organize:
            usr/bin/Xwayland: usr/bin/Xwayland.orig
    patchy:
        after: [plasma]
        plugin: dump
        source: xwayland
    session:
        after: [patchy]
        plugin: dump
        source: session
